name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            APP_DIR="/home/${{ secrets.EC2_USER }}/urban-infra-feedback-system"

            # Clone if folder doesn't exist
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/ShruB1820/urban-infra-feedback-system.git "$APP_DIR"
            fi

            cd "$APP_DIR"

            # Stash local changes to avoid conflicts
            git stash save "auto-stash-before-deploy" || true

            git checkout main
            git pull origin main

            # Backend
            cd backend
            npm install

            # Frontend
            cd ../frontend
            npm install
            npm run build

            # Restart backend
            cd ../backend
            pm2 restart taskmanager || pm2 start server.js --name taskmanager
            pm2 save
          EOF
      

        
#demo
        